format = "$directory$git_status$git_branch$kubernetes$azure$python$all"

[character]
success_symbol = "âœ(bold green) "
error_symbol = "âœ(bold red) "

[kubernetes]
format = '[â›µ$context\($namespace\)](dimmed green) '
disabled = false

[azure]
disabled = false
format = "[$symbol($subscription)]($style) "

[java]
disabled = true

[package]
disabled = true

[status]
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"

[python]
format = '[(\(ğŸ$virtualenv\))]($style)'

[git_status]
disabled = true
